name: My_first_Workflow
on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps: 
            - name: checkout workflow
              uses: actions/checkout@v4

            - name: Welcome message
              run: |
                   echo "welcome to my first github workflow"
                   ls -lrta
                   cat README.md

            - name: Generate ASCII Artwork
              run: cowsay -f dragon "Run for cover, i am a Dragon....ROARRR" >> dragon.txt
             # run: ls

            #- name: Read file
             # run: cat action-test/README.md