name: My_first_Workflow
on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps: 
            - name: Welcome message
              run: echo "welcome to my first github workflow"

            - name: List files
              run: ls

            - name: Read file
              run: cat README.md