name: Generate ASCII Artwork
on: push

jobs: 
    ascii_job:
        runs-on: ubuntu-latest
        steps: 
            - name: checkout Repo
              uses: actions/checkout@v4

            - name: install Cowsay Program
              run: sudo apt-get install cowsay -y

            - name: Execute cowsay CMD
              run: cowsay -f dragon "Run for cover, i am a Dragon....ROARRR" >> dragon.txt

            - name: test file exists
              run: grep -i "dragon" dragon.txt
            
            - name: Read file
              run: cat dragon.txt

            - name: List repo files
              run: ls -lrta