name: matrix-configuration
on: 
    push:
    workflow_dispatch:

jobs:
    deploy:
        strategy: 
          fail-fast: false
          max-parallel: 2 #number of jobs to run at a time.
          matrix: 
            os: [ubuntu-latest, ubuntu-20.04, windows-latest] #create a key-value pair for matrix configs for list of OS.
            images: [hello-world, alpine] #create a key-value pair for matrix configs for list of images.

            exclude: #exclude a matrix from running
               - images: alpine
                 os: windows-latest
            include: #include a new matrix
               - images: amd64/alpine
                 os: ubuntu-20.04
        runs-on: ${{ matrix.os }}
        steps:
            - name: Echo Docker details
              run: docker info

            - name: Run Images
              run: docker run ${{ matrix.images }}